"""scope conversations to notebooks

Revision ID: 1c8f713c30fc
Revises: 7f5d551a1dde
Create Date: 2026-09-24 22:05:01.400872

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c8f713c30fc"
down_revision: str | Sequence[str] | None = "7f5d551a1dde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("notebook_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_conversations_notebook_id"), "conversations", ["notebook_id"], unique=False
    )
    op.create_foreign_key(
        "fk_conversations_notebook_id",
        "conversations",
        "notebooks",
        ["notebook_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_conversations_notebook_id", "conversations", type_="foreignkey")
    op.drop_index(op.f("ix_conversations_notebook_id"), table_name="conversations")
    op.drop_column("conversations", "notebook_id")
    # ### end Alembic commands ###
