"""add chunk end_page

Revision ID: 7f5d551a1dde
Revises: ddb6c0730123
Create Date: 2026-09-22 21:04:35.581196

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f5d551a1dde"
down_revision: str | Sequence[str] | None = "ddb6c0730123"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("end_page", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "end_page")
    # ### end Alembic commands ###
